# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

singleCCDr <- function(cors, init_betas, init_sigmas, nn, lambda, params, blocks, verbose) {
    .Call('Rccdr2_singleCCDr', PACKAGE = 'Rccdr2', cors, init_betas, init_sigmas, nn, lambda, params, blocks, verbose)
}

